[package]
name = "aptos-counter"
version = "1.0.0"
authors = []

[addresses]
aptos_counter = "e23aa62de4861c6fe0579e5c284ea7ad9be5777e61f976bfcc178269791f28fe"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
